---
name: Wheels

on: [push, pull_request, workflow_dispatch]

env:
  REPO_DIR: Fiona
  WHEEL_SDIR: wheelhouse
  SETUPTOOLS_USE_DISTUTILS: stdlib
  BUILD_COMMIT: 1.8.21

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python: ["3.9"]
        platform: ["aarch64"]
        macos-target: ["10.10"]
        include:
          - os: "ubuntu-20.04"
            os-name: "focal"
    env:
      PLAT: "${{ matrix.platform }}"
      MB_PYTHON_VERSION: "${{ matrix.python }}"
    steps:
      - name: Print Target Architecture
        run: echo ${{ matrix.platform }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python on x86_64
        if: matrix.platform != 'aarch64'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Wheel
        if: matrix.platform != 'aarch64'
        run: |
          echo Running x86_64
          .github/workflows/build.sh
          echo Finished running x86_64

      - name: Build on aarch64
        if: matrix.platform == 'aarch64'
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.platform }}
          distro: ubuntu20.04
          run: |
            echo Running build.sh on arm
            echo Target platform: ${{ matrix.platform }}
            echo Emulated platform: $(arch)
            apt-get update -q -y
            apt-get install -q -y python3 python3-pip python-is-python3 git
            apt install docker.io -y
            echo Installed packages
            .github/workflows/build.sh
            echo Finished running arm
          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            REPO_DIR: ${{ env.REPO_DIR }}
            WHEEL_SDIR: ${{ env.WHEEL_SDIR }}
            SETUPTOOLS_USE_DISTUTILS: ${{ env.SETUPTOOLS_USE_DISTUTILS }}
            BUILD_COMMIT: ${{ env.BUILD_COMMIT }}
            PLAT: "${{ matrix.platform }}"
            MB_PYTHON_VERSION: "${{ matrix.python }}"
            MB_ML_VER: "2014"
            BUILD_DEPENDS: "oldest-supported-numpy cython==0.29.26 wheel==0.34.2"
            TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz"
            TRAVIS_OS_NAME: ${{ matrix.os-name }}
            MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}


      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: [build]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
